name: manga_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Umamusume_Star_Blossom.jpg
    - assets/images/Shin_Ootaka_Homare.jpg
    - assets/images/Umamusume_Cinderella_Gray.jpg
    - assets/images/JJK.jpg
    - assets/images/Dandadan.jpg
    - assets/images/One_Piece.jpg
